<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKx5sjiy\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKx5sjiy/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerKx5sjiy.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerKx5sjiy\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerKx5sjiy\appProdProjectContainer([
    'container.build_hash' => 'Kx5sjiy',
    'container.build_id' => '1b0ccf55',
    'container.build_time' => 1671115058,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKx5sjiy');
